CREATE TABLE MEAL_TYPE (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
CODE VARCHAR(100) UNIQUE,
NAME VARCHAR(100) NOT NULL
);

CREATE TABLE MEAL_CATEGORY (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
CODE VARCHAR(100) UNIQUE,
NAME VARCHAR(100) NOT NULL
);

CREATE TABLE MEAL (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
PRICE DOUBLE NOT NULL CHECK(PRICE>0),
MEAL_TYPE_ID BIGINT REFERENCES MEAL_TYPE(ID),
MEAL_CATEGIRY_ID BIGINT REFERENCES MEAL_CATEGORY(ID)
);

CREATE TABLE CUSINE (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL
);

CREATE TABLE LUNCH (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
CUSINE_ID BIGINT REFERENCES CUSINE(ID)
);

CREATE TABLE LUNCH_MENU (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
LUNCH_ID BIGINT NOT NULL REFERENCES LUNCH(ID),
MEAL_ID BIGINT NOT NULL REFERENCES MEAL(ID)
);

CREATE TABLE ORDERS (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ORDERS_NUMBER BIGINT UNIQUE
);

CREATE TABLE ORDER_PART (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ORDER_ID BIGINT NOT NULL REFERENCES ORDERS(ID),
MEAL_ID BIGINT NOT NULL REFERENCES MEAL(ID)
);
